
export const dummyDocuments = [
    {
        id: "DOC-1001",
        name: "Aadhaar_Card_Front.pdf",
        category: "Aadhaar",
        size: "2.4 MB",
        uploadDate: "2026-07-20",
        lastUpdated: "2026-07-21",
        status: "Approved",
        verifiedBy: "Admin Smith",
        verificationDate: "2026-07-21",
        thumbnail: "https://via.placeholder.com/150",
        previewUrl: "https://via.placeholder.com/800x600?text=Aadhaar+Card+Preview",
        remarks: "Clear and legible.",
    },
    {
        id: "DOC-1002",
        name: "PAN_Card_Scanned.pdf",
        category: "PAN",
        size: "1.1 MB",
        uploadDate: "2026-07-21",
        lastUpdated: "2026-07-21",
        status: "Pending",
        verifiedBy: "-",
        verificationDate: "-",
        thumbnail: "https://via.placeholder.com/150",
        previewUrl: "https://via.placeholder.com/800x600?text=PAN+Card+Preview",
        remarks: "",
    },
    {
        id: "DOC-1003",
        name: "10th_Marksheet_Original.jpg",
        category: "10th Marksheet",
        size: "4.5 MB",
        uploadDate: "2026-07-21",
        lastUpdated: "2026-07-21",
        status: "Pending",
        verifiedBy: "-",
        verificationDate: "-",
        thumbnail: "https://via.placeholder.com/150",
        previewUrl: "https://via.placeholder.com/800x600?text=10th+Marksheet+Preview",
        remarks: "",
    },
    {
        id: "DOC-1004",
        name: "Passport_Copy_Page1.pdf",
        category: "Passport",
        size: "3.2 MB",
        uploadDate: "2026-07-19",
        lastUpdated: "2026-07-20",
        status: "Rejected",
        verifiedBy: "Admin Jones",
        verificationDate: "2026-07-20",
        thumbnail: "https://via.placeholder.com/150",
        previewUrl: "https://via.placeholder.com/800x600?text=Passport+Preview",
        remarks: "Image is too blurry. Please re-upload.",
    },
    {
        id: "DOC-1005",
        name: "Degree_Certificate_BTech.pdf",
        category: "Degree Certificate",
        size: "5.0 MB",
        uploadDate: "2026-07-15",
        lastUpdated: "2026-07-16",
        status: "Approved",
        verifiedBy: "Admin Smith",
        verificationDate: "2026-07-16",
        thumbnail: "https://via.placeholder.com/150",
        previewUrl: "https://via.placeholder.com/800x600?text=Degree+Preview",
        remarks: "Verified against university records.",
    },
    {
        id: "DOC-1006",
        name: "Driving_License_Front.jpg",
        category: "Driving License",
        size: "1.8 MB",
        uploadDate: "2026-07-22",
        lastUpdated: "2026-07-22",
        status: "Pending",
        verifiedBy: "-",
        verificationDate: "-",
        thumbnail: "https://via.placeholder.com/150",
        previewUrl: "https://via.placeholder.com/800x600?text=DL+Preview",
        remarks: "",
    }
];

export const dummyActivity = [
    { id: 1, action: "Document Uploaded", docName: "Driving_License_Front.jpg", time: "2 hours ago", type: "upload" },
    { id: 2, action: "Document Approved", docName: "Aadhaar_Card_Front.pdf", time: "1 day ago", type: "approve" },
    { id: 3, action: "Document Rejected", docName: "Passport_Copy_Page1.pdf", time: "2 days ago", type: "reject" },
    { id: 4, action: "Share Link Generated", docName: "Degree_Certificate_BTech.pdf", time: "3 days ago", type: "share" },
];
